export default {
	'app.title': 'ToBeActive',
	'login': 'Přihlášení',
	'login.signIn': 'Přihlásit se',
	'login.signUp': 'Registrovat',
	'login.signIn.question': 'Ještě nemáte účet?',
	'login.signUp.question': 'Už máte účet?',
	'login.signUp.here': 'Zaregistrujte se zde',
	'login.signIn.here': 'Přihlaste se zde',
	'logout': 'Odhlásit se',
	'start': 'Začátek',
	'end': 'Konec',
	'change_language': 'Změnit jazyk',
	'cs': 'Čeština',
	'en': 'Angličtina',
	'change_theme': 'Změnit motiv',
	'required': 'Povinné pole',
	'multisport': 'Multisport',
	'isic': 'ISIC',
	'free_parking': 'Bezplatné parkování',
	'beverage': 'Občerstvení',
	'you_sure': 'Jste si jistí?',
	'yes': 'Ano',
	'no': 'Ne',
	'sc_not_found': 'Sportovní centrum nenalezeno',
	'res_info': 'Informace o rezervaci:',
	'on': 'Dne:',
	'from': 'Od',
	'till': 'do',
	'sport_': 'Sport:',
	'made_on': 'Vytvořeno dne:',
	'cancel_res': 'Zrušit rezervaci',
	'make_res': 'Vytvořit rezervaci',
	'facility': 'Ve sportovním centru:',
	'city_': 'Město:',
	'sport': 'Sport',
	'date': 'Datum',
	'cancel': 'Zrušit',
	'reserve': 'Rezervovat',
	'no_res': 'Zatím nemáte žádné rezervace...',
	'today_res': 'Dnešní rezervace',
	'future_res': 'Budoucí rezervace',
	'past_res': 'Minulé rezervace',
	'enter_city': 'Zadejte prosím město, abyste mohli začít vyhledávat',
	'city': 'Město',
	'search': 'Hledat',
	'must_log_in': 'Pro vytvoření rezervace se musíte přihlásit',
	'open_hours': 'Otevírací hodiny:',
	'badminton': 'Badminton',
	'basketball': 'Basketbal',
	'box': 'Box',
	'dance': 'Tanec',
	'pilates': 'Pilates',
	'soccer': 'Fotbal',
	'squash': 'Squash',
	'swimming': 'Plavání',
	'tennis': 'Tenis',
	'table-tennis': 'Stolní tenis',
	'volleyball': 'Volejbal',
	'sports_': 'Sporty:',
	'sign_register': 'Přihlaste se nebo zaregistrujte',
	'hello': 'Ahoj',
	'what_do': 'Co byste chtěli udělat?',
	'fill_email_pass': 'Prosím vyplňte e-mail a heslo.',
	'unknown_error': 'Došlo k neznámé chybě',
	'notFound': 'Nebylo nalezeno',
	'notFound.body': 'Jejda, zdá se, že tato stránka neexistuje',
	'log_first': 'Pro zobrazení svých rezervací se nejprve přihlaste',
	'not_found_facilities':
		'Bohužel jsme nenašli žádná zařízení odpovídající vašim filtrům. :(',
	'reservations': 'Rezervace',
	'home': 'Domů',
	'email': 'Email',
	'password': 'Heslo'
};
