export default {
	'app.title': 'ToBeActive',
	'login': 'Login',
	'login.signIn': 'Sign in',
	'login.signUp': 'Sign Up',
	'login.signIn.question': 'Do you not have an account yet?',
	'login.signUp.question': 'Do you already have an acount?',
	'login.signUp.here': 'Sign up here',
	'login.signIn.here': 'Sign in here',
	'logout': 'Logout',
	'start': 'Start',
	'end': 'End',
	'change_language': 'Change language',
	'cs': 'Czech',
	'en': 'English',
	'change_theme': 'Change theme',
	'required': 'Required',
	'multisport': 'Multisport',
	'isic': 'ISIC',
	'free_parking': 'Free parking',
	'beverage': 'Beverage',
	'you_sure': 'Are you sure?',
	'yes': 'Yes',
	'no': 'No',
	'sc_not_found': 'Sports Center not found',
	'res_info': 'Reservation info:',
	'on': 'On:',
	'from': 'From',
	'till': 'till',
	'sport_': 'Sport:',
	'made_on': 'Made on:',
	'cancel_res': 'Cancel Reservation',
	'make_res': 'Make a reservation',
	'facility': 'In facility:',
	'city_': 'City:',
	'sport': 'Sport',
	'date': 'Date',
	'cancel': 'Cancel',
	'reserve': 'Reserve',
	'no_res': 'You dont have any reservations...yet',
	'today_res': "Today's reservations",
	'future_res': 'Future reservations',
	'past_res': 'Past reservations',
	'enter_city': 'Please enter a city to start searching',
	'city': 'City',
	'search': 'Search',
	'must_log_in': 'You need to be logged in to make a reservation',
	'open_hours': 'Opening hours:',
	'badminton': 'Badminton',
	'basketball': 'Basketball',
	'box': 'Box',
	'dance': 'Dance',
	'pilates': 'Pilates',
	'soccer': 'Soccer',
	'squash': 'Squash',
	'swimming': 'Swimming',
	'tennis': 'Tennis',
	'table-tennis': 'Table tennis',
	'volleyball': 'Volleyball',
	'sports_': 'Sports:',
	'sign_register': 'Sign in or register',
	'hello': 'Hello',
	'what_do': 'What would you like to do?',
	'fill_email_pass': 'Please fill in email and password.',
	'unknown_error': 'Unknown error occurred',
	'notFound': 'Not Found',
	'notFound.body': 'Oops, looks like this page does not exist',
	'log_first': 'To see your reservations, please log in first',
	'not_found_facilities':
		'Unfortunately we did not find any facilities that match your conditions. :(',
	'reservations': 'Reservations',
	'home': 'Home',
	'email': 'Email',
	'password': 'Password'
};
